---
- name: Setup | copy check_proxy script
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_script }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart service

- name: Setup | set virtual router id
  ansible.builtin.set_fact:
    keepalived_vrid: "{{ 255 | random }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- name: Setup | template keepalived configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_conf }}"
  become: true
...
